// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InputadditionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void inputaddition() {
    // Test name: input addition
    // Step # | name | target | value
    // 1 | open | /Somme/ | 
    driver.get("http://localhost/Somme/");
    // 2 | setWindowSize | 976x1050 | 
    driver.manage().window().setSize(new Dimension(976, 1050));
    // 3 | click | id=nombre1 | 
    driver.findElement(By.id("nombre1")).click();
    // 4 | type | id=nombre1 | 1
    driver.findElement(By.id("nombre1")).sendKeys("1");
    // 5 | type | id=nombre2 | 1
    driver.findElement(By.id("nombre2")).sendKeys("1");
    // 6 | type | id=nombre2 | 1
    driver.findElement(By.id("nombre2")).sendKeys("1");
    // 7 | sendKeys | id=nombre2 | ${KEY_UP}
    driver.findElement(By.id("nombre2")).sendKeys(Keys.UP);
    // 8 | type | id=nombre2 | 2
    driver.findElement(By.id("nombre2")).sendKeys("2");
    // 9 | type | id=nombre2 | 2
    driver.findElement(By.id("nombre2")).sendKeys("2");
    // 10 | sendKeys | id=nombre2 | ${KEY_UP}
    driver.findElement(By.id("nombre2")).sendKeys(Keys.UP);
    // 11 | type | id=nombre2 | 3
    driver.findElement(By.id("nombre2")).sendKeys("3");
    // 12 | sendKeys | id=nombre2 | ${KEY_UP}
    driver.findElement(By.id("nombre2")).sendKeys(Keys.UP);
    // 13 | type | id=nombre2 | 4
    driver.findElement(By.id("nombre2")).sendKeys("4");
    // 14 | click | css=input:nth-child(7) | 
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
  }
}
